firstNames = "Grace Natalia Muldoon,Uzochi,Khai,Rayan Mahdi,Alayna,Sophia,Breanne Grace,Noel Armando,GIOVANA,Carolyn,Julia,Manning,Genevieve Elizabeth Muldoon,Brooks,Vineet Nagendra,Madeline,John,Camille,Thomas,Naomi,Mateen,Tiffany,Maxwell Joshua,Gastón Gabriel,Giuliana ,Danielle,Vaishnava ,Akash,Michael Louis Hugh,Mylie Eva,Carson,Arushi,Angelina,Milo,Sadie Olivia,Felicity,Samantha Grace,Anika,Andy,Joseph,Carter,Laasya,Jyotsna,Austin,Elijah,Sahiba,Jahnavi,Kyla,Sophia,Griffin,Mai,Evgenia,Yinuo Jiang,Jingxuan,Solomon,Susannah,Annabella,Atchaya ,Antariksha,Aidan ,Cecilia,Matthew,Nikolai Evgeni,Tina,Emmalee,Savannah,Lucas,Holly,Emma,Martina Constanza,Sofía Valentina,Marian ,Prisha,Grace,Sudipa,Azul Kamilah,Katherine Emily,Gemma,Jeemin,Bryan,Kinzey ,Mason Alexander,James,Benjamin,Mariam,Emberlynn,Vikram,Mary,Jorge Humberto,Andre,Gideon,Sindia,Leena,Jackson,Jessica,Sophia,Changyang,Nicole,Gabriela Guadalupe,Irene,Joseph,Kris,Ikeoluwa,Vyshnavi ,Mia Sakata,Bristol,Gabrielle,Isabelle,Elisea Amara,Lucia ,Elizabeth".split(",")
lastNames = "Muldoon,Orji,Matsudaira,Zaman,Hu,Li,Graham,Espinosa Santamaría,ROCHA DOS SANTOS,He,Huang,Zhang,Muldoon,Beyer,Vadrevu,Awad,Saleeby,Branch,Gershanik,Long,Hasan,Wang,Chen,Diaz,Lodolo,Franklyn,Ramjass,Ragoo,Gearing,Barna,Fu,Raizada,Li,Baumgartner,McCann,Berling,Dalby,Chegireddy,Chen,Michna,Wildrick,Chintapalli,Venkat,McConkey,Bouchard,Kaur,Kari,Fallis,Wu,Hengelsberg,Tran,Zheltov,Jiang,Zhou,Blecher,Blackford,Liutikas,Muthupalaniappan,Sharma,Ward,King,Oimoen,Pratasenia,Gao,Otipoby,Massey,Askew,Steen,Colarte Delgado ,Contreras Jara,Pavez García,Suárez Agrazal ,Shroff,Yang,Chowdhury,Hernandez Hernandez ,Lam,Muller-Smit,Kim,Li,Clark ,Mickelson,Gessey,Chiu,Doucoure,Thompson,Sharma,Zins,Ibarra Flores,Lee,Shalev,Michael,Dudi,Darin,Wu,Xia,Wang,Martínez González ,Ledezma Hidalgo,Pan,Chen,Lau,Sowemimo,Donthabhaktuni,Stogdill,Hill,Carrasco,Moosman,Jackson,Williams ,Kinghorn".split(",")
states = "Alaska,California,District of Columbia,Kansas,Maryland,Maryland,Virginia,Panama,Brazil,New Jersey,New Jersey,Alaska,Alaska,North Dakota,Alabama,Missouri,Missouri,New Hampshire,Louisiana,Nebraska,Pennsylvania,Pennsylvania,West Virginia,Argentina,Argentina,Trinidad and Tobago,Trinidad and Tobago,Trinidad and Tobago,Texas,Tennessee,Indiana,Virginia,North Carolina,Rhode Island,Rhode Island,Kentucky,Georgia,Louisiana,Mississippi,South Dakota,Tennessee,Connecticut,Connecticut,Maine,Maine,Michigan,North Carolina,Ohio,Ohio,Vermont,New York,South Carolina,South Carolina,Massachussets,New York,Colorado,Illinois,Illinois,Iowa,Wisconsin,Wisconsin,Wisconsin,Florida,Alabama,Kentucky,Mississippi,Nebraska,New Mexico,Florida,Chile,Chile,Panama,Arizona,Delaware,Delaware,Mexico,Arizona,Hawaii,Idaho,Idaho,Montana,Montana,North Dakota,Utah,Utah,Wyoming,Minnesota,Minnesota,Mexico,Nevada,Nevada,Arkansas,Kansas,Wyoming,Michigan,Oklahoma,Oklahoma,Costa Rica,Bolivia,California,Arkansas,Indiana,Texas,Massachussets,Iowa,Oregon,Washington,Washington,New Mexico,Oregon,West Virginia".split(",")
fullNames = []

for i in range(len(firstNames)):
    fullNames.append(firstNames[i] + " " + lastNames[i])

for i in range(len(firstNames)):
    print(firstNames[i], lastNames[i], states[i])

for name in fullNames:
    print(name)